M48
; DRILL file {KiCad 7.0.11} date Monday, September 02, 2024 at 12:26:10 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-02T12:26:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X-2.89Y-18.9
X2.89Y-18.9
T2
X-8.56Y6.02
X-8.56Y3.02
X-8.56Y-2.8
X-8.56Y-5.8
M30
